import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Auth home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-full flex-col items-center justify-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-400 to-slate-800">
        {children}
      </body>
    </html>
  );
}
